import { useState, useEffect, useRef } from 'react'

const API = '/api'

const TYPE_COLORS = {
    plant: '#22c55e', seed: '#4ade80', prep: '#fbbf24',
    care: '#38bdf8', observe: '#a78bfa', plan: '#94a3b8',
}

export default function ActionPlan({ profile, intervention, onBack }) {
    const [plan, setPlan] = useState(null)
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState(null)
    const [activeTab, setActiveTab] = useState('calendar')
    const printRef = useRef()

    useEffect(() => {
        const load = async () => {
            setLoading(true)
            setError(null)
            try {
                const res = await fetch(`${API}/action-plan`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        zip_code: profile.zip_code,
                        intervention,
                        area_sqft: profile.area_sqft,
                        sun: profile.sun_exposure,
                        soil: profile.soil_type,
                    }),
                })
                if (!res.ok) {
                    const body = await res.json().catch(() => ({}))
                    throw new Error(body.detail || 'Failed to generate action plan')
                }
                const data = await res.json()
                setPlan(data)
            } catch (err) {
                console.error('Failed to load action plan:', err)
                setError(err?.message || 'Could not generate action plan')
            }
            setLoading(false)
        }
        load()
    }, [profile, intervention])

    const handlePrint = () => {
        const printContent = printRef.current
        if (!printContent) return
        const w = window.open('', '_blank')
        if (!w) return
        w.document.write(`
      <html><head><title>REWILD Planting Calendar — ${intervention.replace(/_/g, ' ')}</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 24px; color: #1a1a2e; }
        h1 { color: #16a34a; } h2 { color: #374151; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; }
        .month { margin-bottom: 16px; } .task { padding: 4px 0; font-size: 14px; }
        .badge { background: #f0fdf4; color: #16a34a; padding: 2px 8px; border-radius: 4px; font-size: 12px; display: inline-block; margin-right: 8px; }
        .grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px; }
        .dont { color: #dc2626; } table { width: 100%; border-collapse: collapse; } th, td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        @media print { body { padding: 12px; } }
      </style></head><body>
      <h1>🌿 REWILD — ${intervention.replace(/_/g, ' ').toUpperCase()}</h1>
      <p>Zone ${plan.zone} · ${plan.ecoregion} · ${profile.area_sqft} sq ft · Last frost: ${plan.last_frost}</p>
      <h2>📅 Planting Calendar</h2>
      <div class="grid">
        ${Object.entries(plan.planting_calendar).map(([month, tasks]) => `
          <div class="month"><strong>${month}</strong>${tasks.map(t => `<div class="task">${t.icon} ${t.task}</div>`).join('')}${tasks.length === 0 ? '<div class="task" style="color:#999">—</div>' : ''}</div>
        `).join('')}
      </div>
      <h2>🛒 Shopping List</h2>
      <table><tr><th>Item</th><th>Qty</th><th>Notes</th></tr>
        ${plan.shopping_list.map(s => `<tr><td>${s.icon} ${s.item}</td><td>${s.qty}</td><td>${s.note}</td></tr>`).join('')}
      </table>
      <h2>🚫 Common Mistakes to Avoid</h2>
      ${plan.dont_do.map(d => `<p class="dont">❌ ${d}</p>`).join('')}
      <h2>🔧 Seasonal Maintenance</h2>
      ${Object.entries(plan.maintenance).map(([season, tasks]) => `
        <div><strong>${season.charAt(0).toUpperCase() + season.slice(1)}</strong>
        ${tasks.map(t => `<div class="task">• ${t}</div>`).join('')}</div>
      `).join('')}
      <hr><p style="color:#999;font-size:12px">Generated by REWILD Ecological Scenario Engine</p>
      </body></html>
    `)
        w.document.close()
        w.print()
    }

    if (loading) {
        return (
            <div className="loading-screen animate-fade">
                <div className="loading-spinner" />
                <h2>Generating Your Action Plan</h2>
                <p>Building a personalized planting calendar...</p>
            </div>
        )
    }

    if (error) {
        return (
            <div className="error-screen animate-fade">
                <h2>⚠️ Action Plan Error</h2>
                <p>{error}</p>
                <button className="btn-primary" onClick={onBack}>← Back</button>
            </div>
        )
    }

    if (!plan) return null

    return (
        <div className="action-plan animate-in" ref={printRef}>
            <div className="action-plan-header">
                <button className="btn-secondary btn-sm" onClick={onBack}>← Back to Dashboard</button>
                <div className="header-info">
                    <h1>📋 Your Action Plan</h1>
                    <div className="site-summary">
                        <span className="badge badge-green">{intervention.replace(/_/g, ' ')}</span>
                        <span className="badge badge-teal">{plan.ecoregion}</span>
                        <span className="badge badge-sky">Zone {plan.zone}</span>
                        <span className="badge badge-amber">Last frost: {plan.last_frost}</span>
                    </div>
                </div>
                <button className="btn-primary" onClick={handlePrint}>
                    🖨️ Print Calendar
                </button>
            </div>

            {/* Tabs */}
            <div className="action-tabs">
                {[
                    { id: 'calendar', label: '📅 Planting Calendar' },
                    { id: 'prep', label: '🔧 Prep Tasks' },
                    { id: 'shopping', label: '🛒 Shopping List' },
                    { id: 'maintenance', label: '🌿 Maintenance' },
                    { id: 'mistakes', label: '🚫 Don\'t Do' },
                ].map(tab => (
                    <button
                        key={tab.id}
                        className={`action-tab ${activeTab === tab.id ? 'active' : ''}`}
                        onClick={() => setActiveTab(tab.id)}
                    >
                        {tab.label}
                    </button>
                ))}
            </div>

            {/* Calendar Tab */}
            {activeTab === 'calendar' && (
                <div className="calendar-grid animate-in">
                    {Object.entries(plan.planting_calendar).map(([month, tasks]) => (
                        <div key={month} className={`calendar-month glass ${tasks.length > 0 ? 'has-tasks' : 'empty'}`}>
                            <div className="month-header">{month}</div>
                            {tasks.length === 0 ? (
                                <span className="no-tasks">—</span>
                            ) : (
                                tasks.map((t, i) => (
                                    <div key={i} className="calendar-task" style={{ borderLeftColor: TYPE_COLORS[t.type] || '#64748b' }}>
                                        <span className="task-icon">{t.icon}</span>
                                        <span className="task-text">{t.task}</span>
                                    </div>
                                ))
                            )}
                        </div>
                    ))}
                </div>
            )}

            {/* Prep Tab */}
            {activeTab === 'prep' && (
                <div className="prep-list animate-in">
                    {plan.prep_tasks.map((t, i) => (
                        <div key={i} className="prep-task glass" style={{ animationDelay: `${i * 60}ms` }}>
                            <span className="prep-week">Week {t.week}</span>
                            <span className="prep-icon">{t.icon}</span>
                            <span className="prep-text">{t.task}</span>
                        </div>
                    ))}
                </div>
            )}

            {/* Shopping Tab */}
            {activeTab === 'shopping' && (
                <div className="shopping-list animate-in">
                    <div className="shopping-grid">
                        {plan.shopping_list.map((item, i) => (
                            <div key={i} className="shopping-item glass" style={{ animationDelay: `${i * 40}ms` }}>
                                <span className="shop-icon">{item.icon}</span>
                                <div className="shop-info">
                                    <strong>{item.item}</strong>
                                    {item.scientific && <span className="shop-sci">{item.scientific}</span>}
                                    <span className="shop-note">{item.note}</span>
                                </div>
                                <span className="shop-qty">{item.qty}</span>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Maintenance Tab */}
            {activeTab === 'maintenance' && (
                <div className="maintenance-grid animate-in">
                    {Object.entries(plan.maintenance).map(([season, tasks]) => (
                        <div key={season} className="season-card glass">
                            <h3>{season === 'spring' ? '🌸' : season === 'summer' ? '☀️' : season === 'fall' ? '🍂' : '❄️'} {season.charAt(0).toUpperCase() + season.slice(1)}</h3>
                            {tasks.map((t, i) => (
                                <div key={i} className="maint-task">• {t}</div>
                            ))}
                        </div>
                    ))}
                </div>
            )}

            {/* Don't Do Tab */}
            {activeTab === 'mistakes' && (
                <div className="mistakes-list animate-in">
                    {plan.dont_do.map((d, i) => (
                        <div key={i} className="mistake-card glass" style={{ animationDelay: `${i * 80}ms` }}>
                            <span className="mistake-icon">❌</span>
                            <span>{d}</span>
                        </div>
                    ))}
                    <div className="milestones-section">
                        <h3>🎯 Milestones to Watch For</h3>
                        {Object.entries(plan.milestones).map(([year, events]) => (
                            <div key={year} className="milestone-year">
                                <span className="year-badge">Year {year}</span>
                                {events.map((e, i) => (
                                    <div key={i} className="milestone-event">
                                        <span>{e.icon}</span>
                                        <span className="milestone-month">{e.month}</span>
                                        <span>{e.event}</span>
                                    </div>
                                ))}
                            </div>
                        ))}
                    </div>
                </div>
            )}
        </div>
    )
}
